apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-demo
  namespace: default
  labels:
    app: nginx
    env: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
      env: production
  template:
    metadata:
      labels:
        app: nginx
        env: production
    spec:
      nodeSelector:
        disktype: ssd
      initContainers:
      - name: init-busybox
        image: busybox
        command: ['sh', '-c', 'echo Initializing; sleep 5;']
      containers:
      - name: nginx-demo
        image: nginx:1.19.6
        command: ['/usr/sbin/nginx', '-g', 'daemon off;']
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        - name: https
          containerPort: 443
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 250m
            memory: 128Mi