apiVersion: v1
kind: Service
metadata:
  name: {{ app_name }}
  namespace: {{ app_namespace }}
  labels:
    app: {{ labels.app }}
    env: {{ labels.env }}
spec:
  selector:
    app: {{ labels.app }}
  ports:
    {%- for port in ports %}
    - name: {{ port.name }}
      protocol: {{ port.protocol }}
      port: {{ port.containerPort }}
      targetPort: {{ port.containerPort }}
    {%- endfor %}
